stages:
  - test          
  - build
  - package

variables:
  APP_VERSION: $CI_PIPELINE_IID

test:
  stage: test
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - cat config.js

build-job:
  stage: build
  image: node:latest
  script:
    - echo "BUILDING"
    - npm install
    - echo "Build complete."

deploy:
  stage: package
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  script:
    - docker build . -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker image ls

