stages:
  - test          
  - build
  - deploy

test:
  stage: test
  script:
    - cat config.js

build-job:
  stage: build
  script:
    - echo "BUILDING"
    - npm install
    - nmp
    - echo "Compile complete."

deploy:
  stage: deploy
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  script:
    - docker build . -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker image ls
